services:
  gatsun-website:
    build: . # chemin vers le dossier qui contient le Dockerfile
    container_name: gatsun-website
    restart: unless-stopped
    ports:
      - "8080:3000"
    volumes:
      - app-data:/app/app-data
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      RESEND_API_KEY: ${RESEND_API_KEY}

volumes:
  app-data: {} 