services:
  gatsun-calendar:
    build: . # chemin vers le dossier qui contient le Dockerfile
    container_name: gatsun-website
    restart: unless-stopped
    ports:
      - "8080:3000"
    volumes:
      - ./app-data:/app/data
    environment:
      NODE_ENV: production
      DATABASE_URL: "file:/app/data/gatsun-website.db"